export const style = {
  input:
   `peer 
    block 
    w-full 
    appearance-none 
    border-0 
    border-b-2 
    border-gray-300 
    bg-bgLightest 
    px-2.5 
    pb-
    pt-5 
    font-bold
    focus:font-normal
    text-sm-xxx 
    text-gray-900 
    focus:text-primary
    dark:focus:text-primaryD
    focus:border-b-4
    focus:border-primary 
    focus:outline-none 
    focus:ring-0 
    dark:border-gray-600 
    dark:bg-black
    dark:text-white 
    dark:focus:border-primaryD `,
  label: 
   `absolute 
    top-4 
    left-2.5 
    z-10 
    origin-[0] 
    -translate-y-4 
    scale-[65%] 
    transform  
    text-gray-500 
    duration-300 
    peer-placeholder-shown:translate-y-0 
    peer-placeholder-shown:scale-75 
    peer-focus:-translate-y-4 
    peer-focus:scale-75 
    peer-focus:text-primary 
    dark:text-gray-400 
    peer-focus:dark:text-primaryD `,
};